<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win')) Or (!$(RuntimeIdentifier.StartsWith('win')) And !$(RuntimeIdentifier.StartsWith('linux')))">
    <DefineConstants>OS_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <DefineConstants>OS_LINUX</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
  </ItemGroup>
  
</Project>
