<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <DefineConstants>OS_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <DefineConstants>OS_LINUX</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
  </ItemGroup>
  
</Project>
