<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IsTrimmable>true</IsTrimmable>
		<OutputPath>..\0Bins\Other\AssetRipper.Export.UnityProjects\$(Configuration)\</OutputPath>
		<IntermediateOutputPath>..\0Bins\obj\AssetRipper.Export.UnityProjects\$(Configuration)\</IntermediateOutputPath>
		<RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
	</PropertyGroup>

	<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win')) Or (!$(RuntimeIdentifier.StartsWith('win')) And !$(RuntimeIdentifier.StartsWith('linux')))">
		<DefineConstants>OS_WINDOWS</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
		<DefineConstants>OS_LINUX</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AssetRipper.HashAlgorithms" Version="1.0.0" />
		<PackageReference Include="AssetRipper.Mining.PredefinedAssets" Version="1.3.2" />
		<PackageReference Include="AssetRipper.Tpk" Version="1.0.0" />
		<PackageReference Include="AssetsTools.NET" Version="3.0.4" />
		<PackageReference Include="ICSharpCode.Decompiler" Version="8.2.0.7535" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
		<PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\AssetRipper.PackageGuid\AssetRipper.PackageGuid.csproj" />
		<ProjectReference Include="..\AssetRipper.Export.Modules.Audio\AssetRipper.Export.Modules.Audio.csproj" />
		<ProjectReference Include="..\AssetRipper.Export.Modules.Models\AssetRipper.Export.Modules.Models.csproj" />
		<ProjectReference Include="..\AssetRipper.Export.Modules.Shader\AssetRipper.Export.Modules.Shaders.csproj" />
		<ProjectReference Include="..\AssetRipper.Export.Modules.Textures\AssetRipper.Export.Modules.Textures.csproj" />
		<ProjectReference Include="..\AssetRipper.Import\AssetRipper.Import.csproj" />
		<ProjectReference Include="..\AssetRipper.Processing\AssetRipper.Processing.csproj" />
		<ProjectReference Include="..\AssetRipper.Yaml\AssetRipper.Yaml.csproj" />
		<ProjectReference Include="..\RudeShaderMiddleman\RudeShaderMiddleman.Common\RudeShaderMiddleman.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Shaders\Templates\*" />
		<EmbeddedResource Include="Shaders\Templates\*" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="C:\Users\**\.nuget\packages\icsharpcode.decompiler\**\Humanizer\LICENSE" />
		<Content Remove="C:\Users\**\.nuget\packages\icsharpcode.decompiler\**\Pattern Matching.html" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Shaders\CodeTemplates\Billboard.txt" />
	  <None Remove="Shaders\CodeTemplates\Default.txt" />
	  <None Remove="Shaders\CodeTemplates\ParticlesLit.txt" />
	  <None Remove="Shaders\CodeTemplates\SingleColor.txt" />
	  <None Remove="Shaders\CodeTemplates\SingleTexture.txt" />
	  <None Remove="Shaders\CodeTemplates\Templates.json" />
	  <None Remove="Shaders\CodeTemplates\TransparentDiffuse.txt" />
	  <None Remove="Shaders\CodeTemplates\Unlit.txt" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Shaders\CodeTemplates\Billboard.txt" />
	  <EmbeddedResource Include="Shaders\CodeTemplates\Default.txt" />
	  <EmbeddedResource Include="Shaders\CodeTemplates\ParticlesLit.txt" />
	  <EmbeddedResource Include="Shaders\CodeTemplates\SingleColor.txt" />
	  <EmbeddedResource Include="Shaders\CodeTemplates\SingleTexture.txt" />
	  <EmbeddedResource Include="Shaders\CodeTemplates\Templates.json" />
	  <EmbeddedResource Include="Shaders\CodeTemplates\TransparentDiffuse.txt" />
	  <EmbeddedResource Include="Shaders\CodeTemplates\Unlit.txt" />
	</ItemGroup>

</Project>
