<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputPath>..\0Bins\Other\AssetRipper.GUI.Web\$(Configuration)\</OutputPath>
		<IntermediateOutputPath>..\0Bins\obj\AssetRipper.GUI.Web\$(Configuration)\</IntermediateOutputPath>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="StaticContent\after1.png" />
	  <None Remove="StaticContent\after2.png" />
	  <None Remove="StaticContent\before1.png" />
	  <None Remove="StaticContent\before2.png" />
	</ItemGroup>
  
  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('win')) Or (!$(RuntimeIdentifier.StartsWith('win')) And !$(RuntimeIdentifier.StartsWith('linux')))">
    <DefineConstants>OS_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
    <DefineConstants>OS_LINUX</DefineConstants>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AssetRipper.AccurateShaders\AssetRipper.AccurateShaders.csproj" />
		<ProjectReference Include="..\AssetRipper.Decompilation.CSharp\AssetRipper.Decompilation.CSharp.csproj" />
		<ProjectReference Include="..\AssetRipper.Export.PrimaryContent\AssetRipper.Export.PrimaryContent.csproj" />
		<ProjectReference Include="..\AssetRipper.Export.UnityProjects\AssetRipper.Export.UnityProjects.csproj" />
		<ProjectReference Include="..\AssetRipper.GUI.Licensing\AssetRipper.GUI.Licensing.csproj" />
		<ProjectReference Include="..\AssetRipper.GUI.Localizations\AssetRipper.GUI.Localizations.csproj" />
		<ProjectReference Include="..\AssetRipper.Web\AssetRipper.Web.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="StaticContent/css/site.css" />
		<EmbeddedResource Include="StaticContent/favicon.ico" />
		<EmbeddedResource Include="StaticContent/js/site.js" />
		<EmbeddedResource Include="StaticContent/js/commands_page.js" />
		<EmbeddedResource Include="StaticContent\after1.png" />
		<EmbeddedResource Include="StaticContent\after2.png" />
		<EmbeddedResource Include="StaticContent\before1.png" />
		<EmbeddedResource Include="StaticContent\before2.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AssetRipper.Text.Html" Version="1.0.0" />
		<PackageReference Include="NativeFileDialogs.Net" Version="1.1.0" />
		<PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
	</ItemGroup>

</Project>
